/**
 * Curated notification-sound registry — the single source of truth shared by
 * the settings UI, the native channel setup (lib/push-notifications.ts), and
 * the server send-sites (the reminder crons + /api/send-push).
 *
 * The actual audio assets are generated by scripts/gen-notification-sounds.mjs
 * into two places that MUST stay in sync with the `id`s below:
 *   - public/sounds/<id>.wav                       → web in-app preview
 *   - android/app/src/main/res/raw/notif_<id>.wav  → Android channel sound
 *
 * ── Why a channel per sound (Android) ───────────────────────────────────────
 * A NotificationChannel's sound is IMMUTABLE once the channel is created (see
 * the note in lib/push-notifications.ts). So "let the user change the sound"
 * can't mean mutating one channel — it means one channel per sound, with the
 * FCM server routing each push to the channel whose sound the user picked via
 * android.notification.channel_id. `channelIdForSound` is that mapping, and it
 * is used identically on the native side (to create/clean up channels) and on
 * the server (to route the push), so the two never drift.
 *
 * The 'default' option reuses the long-standing 'activity-reminders' channel
 * (declared as the FCM default in AndroidManifest), so existing users keep the
 * system default notification sound with zero migration.
 */

export const DEFAULT_SOUND_ID = 'default'

/** The pre-existing standard-reminder channel (system default sound). Declared
 *  in AndroidManifest as the FCM fallback channel and created on app launch. */
export const DEFAULT_REMINDER_CHANNEL = 'activity-reminders'

/** The pre-existing alarm-type channel: urgent triple-pulse vibration + system
 *  default sound. Used when an alarm-type reminder has the 'default' sound. */
export const DEFAULT_ALARM_CHANNEL = 'activity-alarms-v2'

export interface NotificationSoundDef {
  /** Stored in preferences.notification_sound; also the web file basename. */
  id: string
  /** android res/raw resource name (no extension). Absent for 'default'. */
  rawRes?: string
  /** Web preview asset served from /public. Absent for 'default'. */
  file?: string
  /** Rough "feel" bucket, surfaced in the UI so users can scan soft↔noticeable. */
  intensity: 'soft' | 'balanced' | 'noticeable'
}

/** Display order in settings. 'default' first; then soft → noticeable. */
export const NOTIFICATION_SOUNDS: NotificationSoundDef[] = [
  { id: 'default',                                              intensity: 'balanced'   },
  { id: 'marimba', rawRes: 'notif_marimba', file: '/sounds/marimba.wav', intensity: 'soft'       },
  { id: 'pop',     rawRes: 'notif_pop',     file: '/sounds/pop.wav',     intensity: 'soft'       },
  { id: 'bell',    rawRes: 'notif_bell',    file: '/sounds/bell.wav',    intensity: 'soft'       },
  { id: 'ding',    rawRes: 'notif_ding',    file: '/sounds/ding.wav',    intensity: 'balanced'   },
  { id: 'chime',   rawRes: 'notif_chime',   file: '/sounds/chime.wav',   intensity: 'balanced'   },
  { id: 'alert',   rawRes: 'notif_alert',   file: '/sounds/alert.wav',   intensity: 'noticeable' },
]

const BY_ID = new Map(NOTIFICATION_SOUNDS.map(s => [s.id, s]))

export function isValidSoundId(id: unknown): id is string {
  return typeof id === 'string' && BY_ID.has(id)
}

/** Returns the def for a sound id, falling back to 'default' for unknowns. */
export function getSoundDef(id: string): NotificationSoundDef {
  return BY_ID.get(id) ?? BY_ID.get(DEFAULT_SOUND_ID)!
}

/** Web preview asset path for a sound, or null for the system default (which
 *  has no bundled file — we can't play the OS notification sound in a browser). */
export function soundPreviewSrc(id: string): string | null {
  return getSoundDef(id).file ?? null
}

/**
 * The Android notification-channel id that carries a given sound. The server
 * sends this as android.notification.channel_id; the native side creates a
 * channel with exactly this id and the matching raw sound. If the channel
 * doesn't exist on the device yet, FCM falls back to the manifest default
 * ('activity-reminders'), i.e. the system default sound — a safe degradation.
 */
export function channelIdForSound(id: string): string {
  if (!isValidSoundId(id) || id === DEFAULT_SOUND_ID) return DEFAULT_REMINDER_CHANNEL
  return `reminders-snd-${id}`
}

/**
 * The alarm-type counterpart of channelIdForSound: the channel carrying both
 * the urgent triple-pulse vibration AND the user's selected sound. Used when
 * reminder_type is 'alarm'. 'default' sound reuses the pre-existing
 * 'activity-alarms-v2' channel (urgent vibration + system default sound).
 */
export function alarmChannelIdForSound(id: string): string {
  if (!isValidSoundId(id) || id === DEFAULT_SOUND_ID) return DEFAULT_ALARM_CHANNEL
  return `alarms-snd-${id}`
}

/** Every non-default sound channel id — used by the native side to clean up
 *  stale per-sound channels so the user's Android settings list stays tidy. */
export function allSoundChannelIds(): string[] {
  return NOTIFICATION_SOUNDS
    .filter(s => s.id !== DEFAULT_SOUND_ID)
    .flatMap(s => [channelIdForSound(s.id), alarmChannelIdForSound(s.id)])
}
